<?php

/**
 * Class EF_Input
 */
class EF_Checkbox_Input extends EF_Input
{

    /**
     * @var string
     */
    public static $_TYPE = 'checkbox';

    /**
     * @var array
     */
    protected $defaultAttributes = array(
        'value' => true,
    );

    /**
     * @var array
     */
    protected $defaultSettings = array(
        'label-after' => true,
    );


    /**
     *
     */
    public static function register()
    {
        add_filter('EF_available_inputs',function($inputs){
            $inputs[self::$_TYPE] = array(
                'type' => self::$_TYPE,
                'label' => __('Checkbox input','easy-form'),
                'class' => self::class
            );

            return $inputs;
        });
    }

    /**
     * @return string
     */
    public function getType()
    {
        return self::$_TYPE;
    }


    public function fillValue($data)
    {
        if(isset($data[$this->getAttribute('name')])){
            $this->addAttribute('value',$data[$this->getAttribute('name')]);
        }

     //   die();
        parent::fillValue($data); // TODO: Change the autogenerated stub
    }


    public function getInput()
    {
        if(in_array($this->getValue(),array(true,'on'))) {
            $this->addAttribute('checked',true);
        }

        return parent::getInput();
    }


}